name: Dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/dependencies.yaml'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/dependencies.yaml'
  schedule:
    - cron: '0 2 * * 5'

permissions:
  contents: read

jobs:
  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Download latest version of ResourceHacker
        env:
          ImportDirectoryBuildProps: false
        run: |
          dotnet run ./dotnet-resources/ResourceHacker.csx
          git restore '*.lock.json'
      - name: Check for any changes
        run: |
          if git diff --exit-code --quiet; then
            echo "All files are up to date"
          else
            echo "Files have changed! You need to update the repository."
            echo "Detected changes:"
            git diff --stat
            exit 1
          fi
